### ISSUE TITLE
Wrong track for LMP2 Prototype

### ISSUE THREAD

**Issue by alimoncul** [tmoitie/iRacing-week-planner#113]
LMP2 Prototype Challenge 4th track set as Virginia International Raceway - Full Course on https://iracing-week-planner.tmo.lol/ but on iRacing UI it is the new track

![11](https://user-images.githubusercontent.com/15328038/227791377-e4083f0e-8d67-41ca-a572-f3568c751a8b.png)

**Comment by tmoitie** [comment]
Good spot. Just re-run the script, looks like it's sorted now!
