### ISSUE TITLE
Integrate Sign-In with Google

### ISSUE THREAD

**Issue by jbinventor** [tmoitie/iRacing-week-planner#122]
As a user, I want to sign-in with my Google identity.
I don't want to create a new account for iRacing-week-planner, with another password to remember.

Consider using Sign In with Google for Web: https://developers.google.com/identity/gsi/web/guides/overview?hl=en

**Comment by tmoitie** [comment]
Looks like I was able to just drop this in, so it'll go out with the season update tomorrow. Thanks for the feedback

<img width="893" alt="Screenshot 2023-09-11 at 18 40 48" src="https://github.com/tmoitie/iRacing-week-planner/assets/985557/9e6f96f0-aab4-46ac-9c1c-e005b3cbbe29">
