### ISSUE TITLE
Add a way of updating owned lists when new free items are added

### ISSUE THREAD

**Issue by rickselby** [tmoitie/iRacing-week-planner#123]
I've been away from iRacing for a while, and there's a lot of new free content. I've been through and marked these as owned, but it would be nice if there was a way of updating this automatically.

**Comment by tmoitie** [comment]
<img width="786" alt="Screenshot 2023-12-12 at 17 25 58" src="https://github.com/tmoitie/iRacing-week-planner/assets/985557/b89d91b3-a1dd-4f75-81d8-9459595afa07">

This was always the intended behaviour, and should update automatically the moment it loads up. You can see in the screenshit the free content is unclickably active. Is this affecting cars/tracks or both? Is it content that has been made free to you or made free to all subscribers?

**Comment by rickselby** [comment]
I belive it affected both cars and tracks (it was a while ago now!). It was all content that had been made free in the last ~2 years - e.g. the Formula Vee, Rudskogen Motorsenter. Once I selected the items, they became unclickably active, but they did not appear as content I owned until I did so.

**Comment by tmoitie** [comment]
Finally figured out why it was happening - intended action on load from Local Storage but then wiping out when loading from Firebase! Should now be fixed
