### ISSUE TITLE
Ringmeister car is the car of the first week for the whole season

### ISSUE THREAD

**Issue by marc073** [tmoitie/iRacing-week-planner#129]
In your app the car class for the serie Ring Meister Ricmotech Series is for this season RingMeister23S4.
But when you click on the car class the popup with the available cars shows the car of the first week for the whole season - currently its Aston Martin Vantage GT4
It would be great to see what car is available in which week.
Cheers

**Comment by marc073** [comment]
@Firewolf1337  Thank you for your explanation.
I feared that. But showing the current car would certainly be better than showing the car from week 1 in week 11 ;-) 
Maybe the added value would justify the additional reading, right? At least until iRacing is able to provide the right car for each week 😅

**Comment by tmoitie** [comment]
Hi both. I haven't delved into the API for a while but if it's true that they aren't surfacing the car on a by week basis, this one is going to be very tricky to resolve! My first instinct is to create an override for this fringe case, but I also believe I didn't write the data architecture with this case in mind:- to show a different car for a given series. 

A quick fix would be to override the car for this series with a message like "Week by week" and a modal, which when you press, it explains that the car changes each week and to check iRacing for more detail. Unfortunately this won't be very useful for a user of the IWP, but I think it's better to be honest than wrong.

I've just got back from holiday so I'll spend some time over the next couple of days exploring the API and my own data architecture to see if I can come up with a decent way of dealing with this.

**Comment by tmoitie** [comment]
This is now done with a manual override, and I've added a car column onto the series view. Moving forward will have to manually update the car list but this isn't super onerous, and if I forget then it'll revert back to it's week 1 behaviour until I get around to it

<img width="680" alt="Screenshot 2023-12-12 at 17 23 38" src="https://github.com/tmoitie/iRacing-week-planner/assets/985557/03987b05-0f0b-45de-a821-fe08991f4869">
