### ISSUE TITLE
DraftMasters Car List

### ISSUE THREAD

**Issue by sasvdw** [tmoitie/iRacing-week-planner#133]
I recently planned a content buy for Oval racing using the site. I planned on buying only a specific car and track combo, bur found out in shock that the cars listed for the D-license DraftMaster series was incorrect. It's not NASCAR Trucks, but 1989 NASCAR instead.

I should've double-checked official iRacing resources first, but it would be nice to have it fixed.

Feature request: direct link to the series on the iRacing website. It should make navigating to the relevant content to buy a lot easier.

**Comment by tmoitie** [comment]
Ah shoot. Sorry about that. Unfortunately iRacing's API doesn't expose any information about when a car changes week by week. From what I understand, iRacing manually change the car for the whole series at the start of each week. We only spotted this recently for the Ringmeister series, and I've put a sort of manual override into place. I will now get that done for the DraftMaster.
