### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by tmoitie** [tmoitie/iRacing-week-planner#15]
- [x] Create a translation system
- [x] Create a language switcher
- [x] Spanish
- [x] German
- [x] French
- [x] Portuguese

**Comment by thiagofesta** [comment]
It looks like some of these are complete already.

Just added portuguese (brazil) https://github.com/tmoitie/iRacing-week-planner/pull/38

**Comment by tmoitie** [comment]
Closing in favour of #51
