### ISSUE TITLE
Endurances races not shown

### ISSUE THREAD

**Issue by Fl4t** [tmoitie/iRacing-week-planner#23]
Hello,

First of all, thanks for this website ;-)

I'm not sure if I'm using your tool properly but when I select for example the 8 Feburary it should show the 12h Bathurst but it doesn't. It looks like it's the case also for Endurance Le Mans series

**Comment by Fl4t** [comment]
Hum it's not true for the Endurance Le Mans my bad ;)

**Comment by tmoitie** [comment]
Closing as relates to old season
