### ISSUE TITLE
Site not accessible with www in url

### ISSUE THREAD

**Issue by movedoa** [tmoitie/iRacing-week-planner#26]
So for some reason i cannot access "https://www.iracing-week-planner.tmo.lol" but "https://iracing-week-planner.tmo.lol" is working fine.

The initial Get request never returns.

**Comment by tmoitie** [comment]
Yep, that's intentional. iracing-week-planner is essentially a subdomain of tmo.lol. It's all hosted on cloudfront so setting up a redirect server just for redirecting a sub-subdomain is beyond the scope of what I want to do.
