### ISSUE TITLE
NASCAR iRacing Series - Open and Fixed have no time data shown.

### ISSUE THREAD

**Issue by matthilt** [tmoitie/iRacing-week-planner#27]
Instead of showing the next race time for NiS Open and Fixed it says No time data.
![Untitled](https://user-images.githubusercontent.com/32342794/68532576-f7229e80-02ec-11ea-8c7e-17a2d62e85de.jpg)

Thank you for this tool. Its great.

Edited to add, I have seen this in Chrome and Edge.

**Comment by tmoitie** [comment]
Fixed!
