### ISSUE TITLE
npm start = errors

### ISSUE THREAD

**Issue by oldfart101** [tmoitie/iRacing-week-planner#35]
npm version = 6.14.2, node = 10.15.2

ERROR in ./src/components/modal/CarModal.js
Module not found: Error: Can't resolve '../../data/cars.json' in '/home/andrew/iRacing-week-planner/src/components/modal'

ERROR in ./src/components/modal/FavouriteSeriesModal.js
Module not found: Error: Can't resolve '../../data/season.json' in '/home/andrew/iRacing-week-planner/src/components/modal'

ERROR in ./src/lib/races.js
Module not found: Error: Can't resolve '../data/season.json' in '/home/andrew/iRacing-week-planner/src/lib'

ERROR in ./src/App.js
Module not found: Error: Can't resolve './data/cars.json' in '/home/andrew/iRacing-week-planner/src'

ERROR in ./src/App.js
Module not found: Error: Can't resolve './data/tracks.json' in '/home/andrew/iRacing-week-planner/src'

    [./node_modules/css-loader/dist/runtime/api.js] 2.35 KiB {mini-css-extract-plugin} [built]
ℹ ｢wdm｣: Failed to compile.

**Comment by tmoitie** [comment]
Hi,

I don't intend on storing iRacing's data on github without their permission, so as an alternative the data json files are scraped.

Firstly make sure you have phantomjs running as a port 4444 webdriver, then run:
`IWP_USERNAME=email@email.com IWP_PASSWORD=secret yarn scrapeData` to fill those files in (with your iRacing credentials)
