### ISSUE TITLE
Purchase Guide not working on the website

### ISSUE THREAD

**Issue by sickan90** [tmoitie/iRacing-week-planner#50]
Seems like the purchase guide uses the old seasons data on the iracing-week-panner.tmo.lol website.

To reprocuce:
select  Skip Barber Race Series and iRacing F3 Championship

On week 6 for example it say the track "Belle Isle" is for both series. But the tracks for week 6 this season are "Tsukuba Circuit - 2000 Full" and "Circuit of the Americas - Grand Prix", not "Belle Isle"

**Comment by tmoitie** [comment]
I think it's an off by one error, Belle Isle is the track for week 7 on both… I'll get that sorted.
