### ISSUE TITLE
Races for VRS Global Endurance Series are not available

### ISSUE THREAD

**Issue by jducobu** [tmoitie/iRacing-week-planner#74]

**Comment by tmoitie** [comment]
Thanks for letting me know. I've run a fresh scrape, hope that's sorted everything 👍  (you may need to force cache refresh)

**Comment by jducobu** [comment]
No @tmoitie , that doesn't run, I don't find the serie in the race week list after refreshing the application cache !

**Comment by tmoitie** [comment]
Are you sure? The next scheduled race week for Global Endurance is the 6th so you might need to adjust the date to see the line item

![Screenshot 2021-07-05 at 15 31 53](https://user-images.githubusercontent.com/985557/124487072-2fba9a00-dda6-11eb-8c85-89ca8076af78.png)
