### ISSUE TITLE
Updated data for 2022S1, help needed?

### ISSUE THREAD

**Issue by OSHW-Rico** [tmoitie/iRacing-week-planner#83]
Is the data automatically pulled, if so when? 

If not: Is someone on it already otherwise i would like to help.

**Comment by tmoitie** [comment]
Hi Rico, it's a semi automated process that can only happen once the iRacing website is updated with all the new season details. Therefore it has to be done on next Monday evening/Tuesday morning. The Week 13 data should come through very soon
